import { EXEMPLO_STATES } from './catalog.mjs';

const esc = value => String(value ?? '').replaceAll('&', '&amp;').replaceAll('<', '&lt;')
  .replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#39;');

export function buildShipPage({ status }) {
  const gates = status?.novos || [];
  const cards = gates.map(item => `<article class="card">
    <div class="cardhead"><span class="badge">${item.jevlet ? 'TYPED JUDGMENT' : 'LOCAL FALLBACK'}</span><span class="state">${item.included ? 'Packaged' : item.jevlet ? 'Missing' : 'Built in'}</span></div>
    <h3>${esc(item.build)}</h3><p>${esc(item.resumo)}</p>
    <div class="mono">${esc(item.gate)}(${esc(item.campos.join(', '))})</div>
    <div class="sub">${item.registered ? 'Registered locally · historical certification record is not reverified here' : 'Available as a packaged definition; live results require a connected provider'}</div>
  </article>`).join('');
  const options = gates.map(item => `<option value="${esc(item.gate)}">${esc(item.build)}</option>`).join('');
  const examples = JSON.stringify(EXEMPLO_STATES).replaceAll('<', '\\u003c');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Jev Ship Pack · Jev Flow</title><link rel="icon" href="/logo.svg" type="image/svg+xml"><style>
:root{color-scheme:dark;--bg:#091114;--panel:#111d21;--edge:#294149;--text:#eaf4f4;--muted:#9ab3b8;--mint:#75e2aa;--cyan:#45bfe1}*{box-sizing:border-box}body{margin:0;background:radial-gradient(900px 500px at 80% -10%,#143236,transparent),var(--bg);color:var(--text);font:14px/1.5 Inter,system-ui,sans-serif}.shell{max-width:1280px;margin:auto;padding:30px 22px 70px}header{display:flex;align-items:flex-start;gap:20px;flex-wrap:wrap}h1{font-size:clamp(26px,4vw,42px);margin:0;letter-spacing:-.05em}header p{max-width:720px;color:var(--muted);margin:4px 0 0}nav{margin-left:auto;display:flex;gap:15px;flex-wrap:wrap}a{color:#8ad5ee;text-decoration:none}a:hover{text-decoration:underline}.kicker{font:700 10px ui-monospace,monospace;letter-spacing:.16em;color:var(--mint)}.stats{display:flex;gap:10px;flex-wrap:wrap;margin:24px 0}.stat{padding:11px 17px;border:1px solid var(--edge);border-radius:12px;background:var(--panel)}.stat strong{display:block;font-size:20px;color:var(--mint)}.stat span{font-size:11px;color:var(--muted)}h2{font-size:19px;margin:33px 0 13px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(255px,1fr));gap:12px}.card,.workbench{border:1px solid var(--edge);border-radius:15px;background:linear-gradient(160deg,#14252a,#0e1a1e);padding:17px}.cardhead{display:flex;align-items:center;justify-content:space-between;gap:8px}.badge{font:700 9px ui-monospace,monospace;letter-spacing:.08em;color:var(--mint)}.state{font:600 10px ui-monospace,monospace;color:var(--cyan)}.card h3{font-size:16px;margin:12px 0 5px}.card p{color:#c4d5d8;font-size:12px;min-height:35px;margin:0 0 12px}.mono{font:11px ui-monospace,Consolas,monospace;color:#a8e9c3;overflow-wrap:anywhere}.sub{border-top:1px solid var(--edge);margin-top:12px;padding-top:10px;color:var(--muted);font-size:11px}.workbench{display:grid;grid-template-columns:minmax(220px,1fr) minmax(290px,2fr);gap:18px}.workbench p{color:var(--muted);font-size:12px;margin:6px 0}label{display:block;font-size:12px;color:var(--muted);margin-bottom:5px}select,textarea{width:100%;border:1px solid #3b5660;background:#081216;color:var(--text);border-radius:9px;padding:10px;font:12px ui-monospace,Consolas,monospace}textarea{min-height:165px;resize:vertical}button{border:0;border-radius:9px;background:linear-gradient(135deg,#248f67,#167b8b);color:#fff;font-weight:800;padding:11px 18px;margin-top:9px;cursor:pointer}button:disabled{opacity:.55;cursor:wait}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#071114;border:1px solid var(--edge);border-radius:9px;padding:12px;font:11px/1.5 ui-monospace,Consolas,monospace;color:#bce7e2;max-height:350px;overflow:auto}.note{color:var(--muted);font-size:12px}@media(max-width:700px){.workbench{grid-template-columns:1fr}}
</style></head><body><main class="shell"><header><div><div class="kicker">JEV FLOW / SHIP PACK</div><h1>Small judgments. Clear policy.</h1><p>Ten packaged Jevlet definitions power typed decisions. An eleventh gate suggests CLI commands locally or through Jev. Code owns every action; a connected provider is required for live judgments.</p></div><nav><a href="/jev/flows">Studio</a><a href="/jev/suite">Test suite</a><a href="/jev/battle">Arena</a><a href="/jev/games">Games</a></nav></header>
<div class="stats"><div class="stat"><strong>${status?.packagedJevlets ?? 0}</strong><span>packaged definitions</span></div><div class="stat"><strong>${status?.totalGates ?? 0}</strong><span>decision gates</span></div><div class="stat"><strong>${status?.registeredJevlets ?? 0}</strong><span>registered in this installation</span></div></div>
<h2>Explore the gates</h2><section class="grid">${cards}</section>
<h2>Run a judgment</h2><section class="workbench"><div><label for="gate">Gate</label><select id="gate">${options}</select><p>Examples are synthetic. A live gate sends the state to your configured Jev provider. Empty inputs are skipped locally.</p><p>Source catalog: <a href="${esc(status?.source || 'https://www.shipwithjev.com/')}">shipwithjev.com</a></p></div><div><label for="state">Input state (JSON)</label><textarea id="state" spellcheck="false"></textarea><button type="button" id="run">Run gate</button><pre id="output" aria-live="polite">Choose a gate and inspect its input before running.</pre></div></section>
<h2>Observed activity</h2><section class="workbench" style="display:block"><p>Only decision metadata and a hash of the input enter the local journal. Unknown provider costs remain unknown; savings are not inferred.</p><pre id="report">Loading activity…</pre></section>
</main><script>
(function(){var examples=${examples};var gate=document.getElementById('gate'),state=document.getElementById('state'),run=document.getElementById('run'),output=document.getElementById('output');
function sample(){state.value=JSON.stringify(examples[gate.value]||{},null,2);}gate.addEventListener('change',sample);sample();
run.addEventListener('click',async function(){run.disabled=true;output.textContent='Running…';try{var body=JSON.parse(state.value);if(!body||typeof body!=='object'||Array.isArray(body))throw new Error('State must be a JSON object');var response=await fetch('/api/jev/ship/'+encodeURIComponent(gate.value),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});var result=await response.json();output.textContent='HTTP '+response.status+'\\n'+JSON.stringify(result,null,2);}catch(error){output.textContent='Error: '+error.message;}finally{run.disabled=false;}});
(async function(){try{var response=await fetch('/api/jev/ship/report');var result=await response.json();document.getElementById('report').textContent=JSON.stringify(result,null,2);}catch(error){document.getElementById('report').textContent='Activity unavailable: '+error.message;}})();})();
</script></body></html>`;
}
